### PR TITLE
Swift rewrite

### PR DESCRIPTION
**Pull request by Bright-Shard**
A rewrite of all the Swift code, which minimises calls to `NSApp.sendEvent` (a method which causes random hangs/pauses while we're trying to handle events).

# Bugs
- [ ] The stoplight buttons on the window aren't coloured right on hover. I can't figure out a way to get just the icon to appear, without changing the background.
- [ ] The hit targets for resizing the window might not be the right size. I'm having to manually program window resizes, so I don't know what they normally are sized at, and went for ~7px.
- [x] The mouse cursor doesn't always reset correctly to the arrow cursor after resizing the window. As far as I can tell, this is an issue with `NSCursor` (like a race condition from setting the cursor twice or something), not my code, but it's still an issue.
- [ ] Not all events currently implemented.
- [x] (As noted by Spey) Sometimes the cursor changes to a resize cursor, but dragging doesn't actually resize the window
- [x] macOS doesn't differentiate middle mouse clicks from other mouse buttons. Need to figure out what button number represents the middle mouse button, and use that for middle mouse events.

### CODE REVIEW

**Comment by Bright-Shard** [comment]
<details>
<summary>Features to implement:</summary>

- [x] Window initialization
- [x] Multiple windows
- [ ] OpenGL support
- [ ] Metal support
- [ ] Window deco
- [x] Window resizing events
- [ ] Window resize increments
- [ ] Window transparency
- [ ] Window max/min-imisation
- [ ] Fullscreen
- [ ] Exclusive Fullscreen
- [x] HiDPI (All macs are HiDPI, should work out of the box)
- [ ] Popups
- [ ] Monitor info
- [ ] Video mode query
- [x] Mouse events
- [ ] Set, lock, or confine mouse cursor
- [ ] Custom cursor icon
- [ ] Cursor hittests
- [ ] Touch events
- [ ] Touch pressure
- [ ] Multitouch
- [ ] Keyboard events
- [ ] Drag 'n drop
- [ ] Raw device events
- [ ] Gamepad/joystick events
- [ ] Device movement events

Taken from https://github.com/loki-chat/lokinit/blob/main/FEATURES.md

</details>

<details>
<summary>Events to support:</summary>

- [x] Window resized
- [x] Window moved
- [ ] Window close requested
- [x] Window destroyed
- [ ] Redraw requested
- [x] Focus in
- [x] Focus out
- [ ] File dropped
- [ ] File hovered
- [ ] File hover cancelled
- [ ] Keyboard events:
    - [x] Key press
    - [x] Key release
    - [x] Key repeat
    - [ ] IME commit
- [ ] Mouse events:
    - [x] Pressed
        - [x] Left
        - [x] Middle
        - [x] Right
        - [x] Other
    - [x] Released
        - [x] Left
        - [x] Middle
        - [x] Right
        - [x] Other
    - [x] Moved
    - [x] Entered window
    - [x] Left window
    - [ ] Scroll wheel
- [ ] Touch events:
    - [ ] Started
    - [ ] Moved
    - [ ] Ended
    - [ ] Cancelled

Taken from `EventType` enum.

</details>

**Comment by Speykious** [comment]
I discovered another bug: while resizing, move the cursor very fast to try to shrink the window to 0. The window disappears and never reappears again.

**Comment by Bright-Shard** [comment]
Source for mouse button numbers:
https://github.com/rust-windowing/winit/blob/81fd39485f81bb3345786f86e387bd3aac925d84/src/platform_impl/macos/view.rs#L1032-L1047

**Comment by Bright-Shard** [comment]
Source for keycodes: https://developer.mozilla.org/en-US/docs/web/api/ui_events/keyboard_event_code_values#code_values_on_mac

This may be useable for other platforms as well.

**Comment by Bright-Shard** [comment]
Moved progress tracking to https://github.com/loki-chat/lokinit/issues/3

**Pull request merged**
